#!/bin/sh

# This is a simple script to handle startup and shutdown.

. /etc/rc.conf

log() {
    color="$1"
    shift
    printf "\033[1;3%sm%s\033[00m\n" "$color" "$*"
}

panic() {
    log 1 "There was an error, starting emergency shell. Type exit to continue boot."
    /bin/sh
}

startup() {
    # Mount API filesystems
    log 3 "Mounting API filesystems..."
    mount -t proc proc /proc -o nosuid,noexec,nodev
    mount -t sysfs sys /sys -o nosuid,noexec,nodev
    mount -t tmpfs run /run -o mode=0755,nosuid,nodev
    mount -t devtmpfs dev /dev -o mode=0755,nosuid
    mkdir -p /dev/pts /dev/shm
    mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
    mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec

    # Initialize devices
    log 3 "Setting up loopback device..."
    ip link set up dev lo

    log 3 "Starting mdev..."
    mdev -s
    mdev -df & pid_mdev=$!

    # Set hostname and mount filesystems
    log 3 "Setting hostname..."
    echo "$HOSTNAME" >| /proc/sys/kernel/hostname

    log 3 "Mounting root as readonly..."
    mount -o remount,ro / || panic

    log 3 "Checking filesystems..."
    fsck -ATat noopts=_netdev
    [ $? -gt 1 ] && panic

    log 3 "Mounting all filesystems..."
    mount -o remount,rw / || panic
    mount -a || panic
    swapon -a || panic

    # Kill device manager so that it can be started by runit
    log 3 "Killing device manager..."
    {
        kill $pid_mdev
        command -v mdev > /proc/sys/kernel/hotplug
    } 2> /dev/null

    # Start service manager (busybox runit)
    log 3 "Starting services..."
    exec runsvdir -P "$SV_DIR" &

    # Calculate boot time
    IFS=. read -r boot_time _ < /proc/uptime
    log 2 "Boot completed in $boot_time seconds."
}

shutdown() {
    # Stop all running services
    log 3 "Stopping services..."
    sv force-shutdown /var/service/* > /dev/null 2>&1

    # Kill running processes
    log 3 "Sending TERM signal to all processes..."
    kill -s TERM -1
    log 3 "Sending KILL signal to all processes..."
    sleep 2
    kiss -s KILL -1

    # Unmount filesystems
    log 3 "Unmounting all filesystems..."
    swapoff -a
    umount -rat nosysfs,proc,devtmpfs,tmpfs
    mount -o remount,ro /
    sync
}

case $1 in
    startup)
        startup;;
    shutdown)
        shutdown;;
    *)
        echo "Usage: $0 [startup | shutdown]";;
esac
